### ISSUE TITLE
Compilation warning regarding crypto:md5/1.

### ISSUE THREAD

**Issue by TrevorS** [erlcloud/erlcloud#187]
Erlang 17.5

```
==> erlcloud (compile)
Compiled src/erlcloud_xml.erl
src/erlcloud_util.erl:38: Warning: crypto:md5/1 is deprecated and will be removed in in a future release; use crypto:hash/2
```

Thanks!

**Comment by scribnar** [comment]
This issue is still there in Erlang/OTP 18. Below is the warning. 

src/erlcloud_util.erl:38: Warning: crypto:md5/1 is deprecated and will be removed in in a future release; use crypto:hash/2

**Comment by motobob** [comment]
addressed

**Comment by TrevorS** [comment]
:+1:
