### ISSUE TITLE
Transition modules away from raising errors

### ISSUE THREAD

**Issue by jasonwebster** [erlcloud/erlcloud#207]
I know that the preferred way of introducing new APIs is using the request2 series of methods that return `{error, Reason}` tuples instead of using `erlang:error`.  @ransomr In the past, you've mentioned that in the case of existing APIs, backwards compatibility is important, and that you'd recommend creating all new modules for existing services that implement the new return values. I'd like to start in on doing that for at least a couple services (SQS and SNS), and just wanted to confirm that that is still the preferred approach, over say, releasing a major version of the library.

**Comment by ransomr** [comment]
Yes, I would prefer new modules. Thanks.

**Comment by motobob** [comment]
@jasonwebster new modules or new funs are both good. Closing this as I suppose the question was answered.
