### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JustMikey** [erlcloud/erlcloud#230]
Why is there absolutely not any documentation? There is not a wiki page, there are no comments in the code and whatnot, what is the reason behind it?

**Comment by ransomr** [comment]
Contributions of documentation are welcome. Some modules are documented, but there is plenty more that could be improved.

**Comment by waisbrot** [comment]
https://hexdocs.pm/erlcloud/

Bam! Documentation!

(It's just the documentation that was already present in the code-comments, but hey...)

**Comment by motobob** [comment]
readme was updated on how to use the lib and configure it. edocs were added. in 2.0.5
