### ISSUE TITLE
More control over retries, timeouts and backoff for DynamoDB

### ISSUE THREAD

**Issue by jonasschmidt** [erlcloud/erlcloud#235]
Right now, the number of retries/attempts is hard-coded to `10` in `erlcloud_ddb_impl`. I think it would be very beneficial to have this configurable.

The same goes for the timeout value for the first request, which is hard-coded to 1s (`#aws_config.timeout` is only used for subsequent requests). There's a comment in the code saying `Shorter timeout on first request.`, but we might actually want to have a shorter timeout than 1s for all requests (including the first).

For the backoff, the option to pass a backoff function as a config setting could also be a useful addition.

**Comment by ransomr** [comment]
The number of attempts and the backoff time can be changed by providing your own `ddb_retry` function. Timeout is not currently easy to configure - I would welcome a PR that would let your provide a timeout function.

**Comment by jonasschmidt** [comment]
Ah ok, that's great. I'll try to prepare a PR for the timeout configuration.

**Comment by motobob** [comment]
this has been addressed in #261
