### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by ransomr** [erlcloud/erlcloud#239]
I've changed jobs and will no longer be working with Erlang or AWS, so I'm looking for someone to take over maintenance of erlcloud. @motobob @nalundgaard @smilerlee you have been the most active recently, any interest? (cc: @gleber)

**Comment by motobob** [comment]
@ransomr, we (@nalundgaard and myself) are happy to take over the maintenance of the root fork of `erlcloud`.

**Comment by smilerlee** [comment]
@ransomr, I'm glad to maintain this repo as well.

**Comment by gleber** [comment]
Sounds good. Since Randomr has referenced @motobob first, I am giving you access right now.

What do you folks think about moving this repo to a standalone organization?

**Comment by motobob** [comment]
@gleber thank you. 
Are you talking about creating https://github.com/erlcloud/erlcloud/ and making it the root fork? 
We can, but looking at https://github.com/gleber/erlcloud/graphs/traffic this still has the majority of the clones and it should continue being root. Otherwise all those people will stop getting updates.  

Also, if you just want to transfer the ownership completely you can always move it to [Alertlogic] (https://github.com/alertlogic/erlcloud). It's has lots of updates where we are just late in propagating them to the upstream as there were some minor incompatibilities introduced over the course of time.

**Comment by ransomr** [comment]
I think you can just transfer ownership and all forks will point at the new root (erlcloud/erlcloud). If you then fork into gleber/erlcloud then people using rebar should continue to work. I don't think it would take long or cause many problems and would be much better than having in a personal or company github account.

**Comment by gleber** [comment]
I think that the designated organization is better than company account, which is better than personal account. I have no experience with transferring ownership, but https://help.github.com/articles/transferring-a-repository/ states:

> In addition to redirecting web traffic, all git clone, git fetch, or git push
> operations targeting the previous location will continue to function as
> if made on the new location

This means that most of normal operations on the repo will continue working (including references in rebar.config files). Later we could clean up these references by sending bunch of PRs to most prominent users.

What do you think? If there are no objections in few days, I'll create the organization account and add @ransomr and @motobob as owners/admins/root there too.

**Comment by gleber** [comment]
Nota bene from the same source:

> Warning: If you create a new repository under your account with the same name as the transferred repository, existing redirects to the transferred repository will break. Instead, use a different name for the new repository.

**Comment by motobob** [comment]
@gleber I have no objections. I just have a preference regarding having it in alertlogic org to make it slightly easier for us, We have handful of devs actively adding feature to `erlcloud` together with AWS adding new things. Also, I bet we will actively maintain this direction for at least 3+ years from now.

In any case, as you are the owner it's up to you to make the final call and we will happily maintain it in any case.

**Comment by gleber** [comment]
@motobob Moving it to AlertLogic would require deleting your existing fork from your organization and transfering this fork's ownership to alertlogic org (and later you'd be able to merge in your existing diffs between these forks). Without these steps, GitHub redirects won't work.

**Comment by gleber** [comment]
I see that diff between root fork and alertlogic fork is huge:
https://github.com/gleber/erlcloud/compare/master...alertlogic:master

Given the necessity of doing delete-and-transfer operations to ensure redirects in place, you'd have a lot of work to merge all these changes back without breaking other people using this code. @motobob What do you think to do here? Maybe let's leave the repo here for now, while you folks are working on merging your changes in and later, when the diff is much smaller, transfer the repo ownership. Just thinking out loud.

**Comment by smilerlee** [comment]
As I see it, leaving this repo its original position here is a much simpler solution, since lots of Erlang repos are in personal namespaces, there isn't any necessities to transfer it to a standalone organization namespace.

**Comment by waisbrot** [comment]
As a regular user of erlcloud, moving it to an organizational repo is attractive because it makes it clearer that this is the correct fork (and not ransomr/erlcloud or smilerlee/erlcloud, etc). It also displays the collaborators more prominently. Neither of those are very strong reasons to prefer it, though.

**Comment by smilerlee** [comment]
@waisbrot yes! that's true to new users, thus I vote for `gleber/erlcloud`, and `erlcloud/erlcloud`, not for `alertlogic/erlcloud`.

**Comment by motobob** [comment]
folks. let's just do it, specifically `erlcloud/erlcloud` and let the contribution continue. 
@gleber will you be able to do it? 
Please add me, @ransomr, @smilerlee, @nalundgaard  and youself as owners of that.

**Comment by nalundgaard** [comment]
I am also +1 on `erlcloud/erlcloud`, it sounds like the right thing for the project.

**Comment by ransomr** [comment]
Also +1 on erlcloud/erlcloud. Seems like the right thing and switching won't cause much pain.

**Comment by gleber** [comment]
Looks like we have a consensus :) @motobob I'll do it in the evening (5-6 hours from now) when I'm back home

**Comment by gleber** [comment]
I think this is solved
