### ISSUE TITLE
Handle "503 Slow Down" response for S3

### ISSUE THREAD

**Issue by jmglov** [erlcloud/erlcloud#248]
As per http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html , S3 can return a `503 Slow Down` error response when the request rate is too high. It would be fantastic if erlclould could handle this so that client code doesn't have to.

This response is not just used by S3, so the error handling logic might be good to implement at the lowest possible level so that other services can also benefit.

**Comment by kkuzmin** [comment]
erlcloud_s3 handles this already. https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_s3.erl#L1144-L1148
Just enable retries in ```#aws_config{retry = erlcloud_retry:default_retry/1}```

**Comment by jmglov** [comment]
@kkuzmin Great, thanks!

**Comment by motobob** [comment]
closing this as already implemented

**Comment by jmglov** [comment]
@kkuzmin Do you have any idea how to do this in Elixir?

In Erlang, it looks like I should do something like this, right?

```erl
erlcloud_aws:update_config(#aws_config{retry = erlcloud_retry:default_retry/1})
```

If that is how to do it, I'm not quite sure how to translate it to Elixir. If this is too off-topic, I'll take it to the Elixir Slack or mailing list, but I figured it was worth a try to ask here. :)

**Comment by motobob** [comment]
@velimir0xff may be you can advice ^?

**Comment by velimir0xff** [comment]
in Elixir I'd write something like that:
```elixir
defmodule Records do
  require Record
  # ...
  Record.defrecord :aws_config, Record.extract(:aws_config, from_lib: "erlcloud/include/erlcloud_aws.hrl")  
  # ...
end

defmodule Config do
  require Records

  def update(config) do
    # ...
    :erlcloud_aws.update_config(
      Records.aws_config(config, retry: &:erlcloud_retry.default_retry/1)
    )
    # ...
  end
end

```

**Comment by jmglov** [comment]
@velimir0xff Thanks! I'll try that out.

**Comment by jmglov** [comment]
@velimir0xff I tried out your suggestion, and am seeing a socket timeout when calling `:erlcloud_aws.update_config/1`. I've included an IEx session below.

Do you have any idea what I'm be doing wrong?

```
iex(1)> s3 = :erlcloud_s3.new("ACCESS_KEY", "SECRET_KEY")
{:aws_config, ...,
 'https://', 's3.amazonaws.com', 80,
 :default, &:erlcloud_retry.no_retry/1}
iex(2)> AWS.Config.update(s3)
{:error, {:socket_error, :timeout}}
iex(4)> AWS.Records.aws_config(s3, retry: &:erlcloud_retry.default_retry/1)
{:aws_config, ...,
 'https://', 's3.amazonaws.com', 80,
 :default, &:erlcloud_retry.default_retry/1}
iex(5)> :erlcloud_aws.update_config(AWS.Records.aws_config(s3, retry: &:erlcloud_retry.default_retry/1))
{:error, {:socket_error, :timeout}}
```
