### ISSUE TITLE
Handle "307 Temporary Redirect" in erlcloud_s3:get_object

### ISSUE THREAD

**Issue by jmglov** [erlcloud/erlcloud#249]
If one tries to get an S3 object from a newly created bucket, S3 may respond with a `307 Temporary Redirect` with a body like this:

```xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message><Bucket>com.foo.some-bucket</Bucket><Endpoint>com.foo.some-bucket.s3-eu-west-1.amazonaws.com</Endpoint><RequestId>F617F068F78EC5E4</RequestId><HostId>WQRUIQqx0rXpUmofEO5F46R09VA45tnHYqrC6DS6ZdI4ti086r9C2mfcilx4rHkPsPVUf93FWAE=</HostId></Error>
```

It would be nice if erlcloud would automatically follow the redirect.

I've grepped the code and it seems like it is not currently supported, but I may be missing something.

**Comment by motobob** [comment]
this is implemented in https://github.com/alertlogic/erlcloud if you wish to switch. 
@kkuzmin what about PRing back all S3 updates of ours to upstream?

**Comment by jmglov** [comment]
@motobob Thanks! I may well switch over. I guess you guys at Alert Logic are using AWS pretty heavily?

**Comment by motobob** [comment]
yes we do and our fork is really ahead of the upstream. we just failed to merge it back long time ago and now they are quite diverged.

**Comment by jmglov** [comment]
@motobob Is your fork feature-complete with upstream?

**Comment by motobob** [comment]
@jmglov yes and it has quite a lot of new features in it. However, there are several APIs not 100% compatible, e.g. ELB ones.

**Comment by jmglov** [comment]
@motobob Thanks, sounds like switching is a good idea for me, then. :)

**Comment by motobob** [comment]
in any case it still makes sense to merge all the goodies into upstream, it's just a huge pile work at the moment.

**Comment by jmglov** [comment]
@motobob Absolutely, but I understand that it can be loads of work.

**Comment by motobob** [comment]
@jmglov please give a try with our fork, if all tests pass for you. please close this issue

**Comment by jmglov** [comment]
@motobob Will do as soon as I figure out how to handle the config in Elixir. :)

**Comment by jmglov** [comment]
@motobob Unfortunately, I can't get your fork to compile in Elixir. Here's what I have in my `mix.exs`:

```elixir
  defp deps do
    [...,
     {:erlcloud, git: "https://github.com/alertlogic/erlcloud", tag: "v1.0.7"},
     ...]
  end
```

And here's the compile error I get:

```
==> covertool (compile)
ERROR: compile failed while processing /home/jmglov/Documents/code/media_pipeline_vod_service/deps/covertool: {'EXIT',{undef,[{rebar_utils,find_files_by_ext,["src",".abnf",true],[]},
                {rebar_base_compiler,run,8,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,69}]},
                {rebar_core,run_modules,4,[]},
                {rebar_core,execute,6,[]},
                {rebar_core,maybe_execute,8,[]},
                {rebar_core,process_dir1,7,[]},
                {rebar_core,process_commands,2,[]},
                {rebar,main,1,[]}]}}
** (Mix) Could not compile dependency :covertool, "/home/jmglov/.mix/rebar compile skip_deps=true deps_dir="/home/jmglov/Documents/code/media_pipeline_vod_service/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile covertool", update it with "mix deps.update covertool" or clean it with "mix deps.clean covertool"
```

Any ideas here?

**Comment by motobob** [comment]
building issues should be already resolved by now and we going to merge AL fork in a bit as per #319.

so closing this
