### ISSUE TITLE
Bad Request when calling erlcloud_elb  de/register_instance

### ISSUE THREAD

**Issue by posilva** [erlcloud/erlcloud#250]
I am trying to register an instance using erlcloud but it keeps giving me the 400 Bad Request.

I there are no tests for erlcloud_elb module.

Any ideia why is this happening?

Thank you

**Comment by motobob** [comment]
1) please post the code example you have and the error message.
2) most commonly error in this case is the Config is not initialised or initialised with a wrong `elb_host` endpoint.

**Comment by posilva** [comment]
I have tested in the console "erl" and I am getting "There is no ACTIVE Load Balancer named 'MyELB" and i have for sure the elb created.   

erlcloud_elb:register_instance("MyELB", "i-32464fe").

Do you know what is the elb_host that i must use for "us-west-2" I have tried several combination but no success.

thank you in advance

**Comment by motobob** [comment]
http://docs.aws.amazon.com/general/latest/gr/rande.html#elb_region  -> `elasticloadbalancing.us-west-2.amazonaws.com`

given the fact that you run it via console without setting Config I suppose you run it from the instance directly in AWS.
Try out: 
```erlang
Cfg = erlcloud_aws:default_config(),
erlcloud_elb:register_instance("MyELB", "i-32464fe", Cfg#aws_config{elb_host = "elasticloadbalancing.us-west-2.amazonaws.com"}).
```

**Comment by posilva** [comment]
It's solved i didn't found that elb regions hosts page, and tried with several without success.

This time it worked.

Thank you very much.
