### ISSUE TITLE
0.13.0 hex package

### ISSUE THREAD

**Issue by Licenser** [erlcloud/erlcloud#254]
It would be great to get the 0.13.0 as a hex package :)

**Comment by waisbrot** [comment]
I said I would handle the Hex packaging for them, but I missed that there was a 0.13.0 release. Sorry.

I just published a 0.13.0, and I removed the listed "meck" dep while I was at it.

**Comment by Licenser** [comment]
awesome! thank you so much! :D

**Comment by smilerlee** [comment]
Thanks @waisbrot , but how about publish the tag 0.12.0 instead?
