### ISSUE TITLE
lhttpc unavaliable 

### ISSUE THREAD

**Issue by sonicgao** [erlcloud/erlcloud#263]
==> erlcloud (get-deps)
Pulling lhttpc from {git,"git://github.com/talko/lhttpc",{tag,"1.4.0"}}
Cloning into 'lhttpc'...
fatal: remote error:
  Repository not found.

**Comment by motobob** [comment]
WOW. that was just deleted and really worked yesterday

**Comment by sonicgao** [comment]
yeah, are we have alternative version?

**Comment by motobob** [comment]
yes...we can fall back to original https://github.com/esl/lhttpc/releases/tag/1.3.0...which will hopefully not get deleted as this is ESL

**Comment by motobob** [comment]
or let me see if we have 1.4.0 already checked out anywhere...

**Comment by goodgoblin** [comment]
in case it helps -- I uploaded what I had locally from my most recent build here:
https://github.com/goodgoblin//lhttpc 
Original source was downloaded on Feb 1, 2016

**Comment by motobob** [comment]
already almost done in https://github.com/erlcloud/lhttpc/pull/1

**Comment by smilerlee** [comment]
@motobob Seems I also got `1.2.6`, `1.3.0` and `1.4.0` checked out here. Need I upload to `erlcloud/lhttpc`?

**Comment by ASCrookes** [comment]
Was there a reason the `talko/lhttpc` branch was being used that might introduce some bugs switching to the original?

**Comment by motobob** [comment]
@smilerlee thank you. I recall you've changed the header processing in 1.4.0. please check erlcloud/lhttpc#1 is a valid and matches your copy. If not please PR your version there.

@ASCrookes yes, there were slight changes...

**Comment by smilerlee** [comment]
@motobob me? changed the header processing? I believe it's not me :)

**Comment by derek121** [comment]
I just came across this as well. Will you be changing erlcloud's rebar.config accordingly?

**Comment by motobob** [comment]
yes. we will fix it all up shortly.

**Comment by smilerlee** [comment]
@derek121 this will be fixed soon.

**Comment by smilerlee** [comment]
fixed. thanks for all of your help.
