### ISSUE TITLE
Remove Meck for "prod" like setup

### ISSUE THREAD

**Issue by cystbear** [erlcloud/erlcloud#265]
Hi, 
there is issue: that `Meck` is only tests dependency.
Is any way to remove it from "prod style" deps?

Kinda https://github.com/tapsters/erlcloud/commit/4c04581e772133d83d245e7be12e8701adba114e

I do not want to use fork, but I have to.

**Comment by waisbrot** [comment]
IMO, the best solution is to use rebar3, which handles this test/not-test separation. I have a PR to upgrade to rebar3 at #256, but I need to update it.

If you use rebar2, then you should stay on your fork.

**Comment by cystbear** [comment]
thanks for answer, will wait rebar3 support.

**Comment by motobob** [comment]
@waisbrot given that recently we moved lhttc 1.4.0 to https://github.com/erlcloud/lhttpc you PR #256 could be updated.  I'll appreciate you assistance with publishing hex pkg for `lhttpc` and we will finally have all the bits in place to close rebar3 and have it available for all.

**Comment by motobob** [comment]
please use rebar3 build as https://github.com/erlcloud/erlcloud/pull/256 is released. 
closing this.
if you have any more issues please re-open
