### ISSUE TITLE
rebar 2 build still requires meck, hex package no longer requires it

### ISSUE THREAD

**Issue by nickveys** [erlcloud/erlcloud#267]
Just updated to 0.13 and everything worked fine until I cleaned my dependencies and re-built.  Now meck is no longer pulled down, but the rebar2 config (https://github.com/erlcloud/erlcloud/blob/master/rebar.config.script) still requires it.  Breaks compilation of erlcloud with:

````
WARN:  Expected <<myapp>>/_build/dev/lib/meck to be an app dir (containing ebin/*.app), 
  but no .app found.
==> erlcloud (compile)
WARN:  Expected <<myapp>>/_build/dev/lib/meck to be an app dir (containing ebin/*.app), 
  but no .app found.
Dependency not available: meck-.* ({git,
                                       "https://github.com/eproxus/meck.git",
                                       {tag,"0.8.4"}})
ERROR: compile failed while processing <<myapp>>/deps/erlcloud: rebar_abort
** (Mix) Could not compile dependency :erlcloud, "/Users/nick/.asdf/installs/elixir/1.2.0/.mix/rebar 
  compile skip_deps=true deps_dir="<<myapp>>/_build/dev/lib"" command failed. You can
  recompile this dependency with "mix deps.compile erlcloud", update it with 
  "mix deps.update erlcloud" or clean it with "mix deps.clean erlcloud"
````

If I comment meck out, it builds, but I'm sure that's not the proper fix, since your tests must still need it, otherwise I'd send a PR!

**Comment by waisbrot** [comment]
When I run locally (or under the Travis tests) with Rebar 3, I either run `rebar3 compile` which does _not_ fetch meck and is happy or I run `rebar3 eunit` which _does_ fetch meck and is also happy. When I run with Rebar 2, the `rebar.config.script` injects meck as a dependency (rebar 2 doesn't differentiate between test dependencies and build dependencies) and things work.

From what you've posted, I assume you're using "mix" as your build tool. I haven't tested this (and am not actually sure how to test, since I've never done an Elixir project). If you made a PR with some additions to the `Makefile` and `.travis.yml` files to demonstrate the failure, that would be very helpful.

**Comment by motobob** [comment]
@nickveys thank you for reporting the issue. strangely that worked great on my setup and same as inside travis.ci where we specifically check that rebar2 build passes.
Just in case, notice the `get-deps` vs `deps` difference.

this is my output:
```sh
mbr13_ebob:erlcloud ebob$ rm -rf deps
mbr13_ebob:erlcloud ebob$ make deps
make: *** No rule to make target `deps'.  Stop.
mbr13_ebob:erlcloud ebob$ make get-deps
==> erlcloud (get-deps)
Pulling meck from {git,"https://github.com/eproxus/meck.git",{tag,"0.8.4"}}
Cloning into 'meck'...
Pulling jsx from {git,"git://github.com/talentdeficit/jsx.git",{tag,"2.8.0"}}
Cloning into 'jsx'...
Pulling lhttpc from {git,"git://github.com/talko/lhttpc",{tag,"1.4.0"}}
Cloning into 'lhttpc'...
==> meck (get-deps)
==> jsx (get-deps)
==> lhttpc (get-deps)
mbr13_ebob:erlcloud ebob$ make eunit
==> meck (compile)
Compiled src/meck_util.erl
Compiled src/meck_ret_spec.erl
Compiled src/meck_proc.erl
Compiled src/meck_matcher.erl
Compiled src/meck_history.erl
Compiled src/meck_expect.erl
Compiled src/meck_cover.erl
Compiled src/meck_code.erl
Compiled src/meck_args_matcher.erl
Compiled src/meck_code_gen.erl
Compiled src/meck.erl
==> jsx (compile)
Compiled src/jsx_verify.erl
Compiled src/jsx_to_term.erl
Compiled src/jsx_encoder.erl
Compiled src/jsx_to_json.erl
Compiled src/jsx_consult.erl
Compiled src/jsx_config.erl
Compiled src/jsx.erl
Compiled src/jsx_parser.erl
Compiled src/jsx_decoder.erl
==> lhttpc (compile)
Compiled src/lhttpc_sup.erl
Compiled src/lhttpc_sock.erl
Compiled src/lhttpc_lib.erl
Compiled src/lhttpc_manager.erl
Compiled src/lhttpc.erl
Compiled src/lhttpc_client.erl
==> erlcloud (compile)
==> erlcloud (eunit)
  All 612 tests passed.
mbr13_ebob:erlcloud ebob$ 
```

please provide more details to the issue so we could resolve it for you

**Comment by nickveys** [comment]
I am using mix for this, so I'll see if I can isolate what it's doing differently to get you more info or a PR...  Thanks for the extra info!

**Comment by motobob** [comment]
@nickveys can you post your `*.exs` file here to see if we spot any issues?
also it would be great to have PR which will just enable basic Elixir build of `erlcloud`.

**Comment by nickveys** [comment]
I've noticed that it'll happen even with a completely empty, new project.  With `mix` installed, if you do the following:

    mix new foo
    cd foo
    vim mix.exs

Change `deps` to be:

    defp deps do
      [{:erlcloud, "~> 0.13"}]
    end

Then run:

    mix do deps.get, deps.compile

You should get something akin to:

```
WARN:  Expected /Users/nick/Development/foo/_build/dev/lib/meck to be an app dir 
  (containing ebin/*.app), but no .app found.
==> erlcloud (compile)
WARN:  Expected /Users/nick/Development/foo/_build/dev/lib/meck to be an app dir 
  (containing ebin/*.app), but no .app found.
Dependency not available: meck-.* ({git,
                                       "https://github.com/eproxus/meck.git",
                                       {tag,"0.8.4"}})
ERROR: compile failed while processing /Users/nick/Development/foo/deps/erlcloud: 
  rebar_abort
** (Mix) Could not compile dependency :erlcloud, "/Users/nick/.asdf/installs/elixir/1.2.3/.mix/rebar 
  compile skip_deps=true deps_dir="/Users/nick/Development/foo/_build/dev/lib"" command failed.
  You can recompile this dependency with "mix deps.compile erlcloud", update it with 
  "mix deps.update erlcloud" or clean it with "mix deps.clean erlcloud"
```

**Comment by nickveys** [comment]
If I move `jsx` and `meck` around, nothing changes, still breaks needing `meck`.

But!  If I change this, in rebar.config.script:

    case erlang:function_exported(rebar3, main, 1) of

to

    case true or erlang:function_exported(rebar3, main, 1) of

Forcing rebar3 to be assumed, it compiles fine.  So it seems like maybe the `erlang:function_exported` check isn't enough to properly detect rebar3 during a build using mix?  Anything useful there?

**Comment by waisbrot** [comment]
OK, I understand. `mix` uses Hex to fetch the dependencies, which do not include Meck. Then it calls rebar2 to build (but not fetch deps!) and rebar2 goes looking for meck.

Change your dependency to force it to use rebar3:
```
{:erlcloud, "~> 0.13", manager: :rebar3}
```

This compiles for me (and fails when I let it default to rebar2).

**Comment by motobob** [comment]
@waisbrot yep. that works. So at least, this definitely calls for a readme update, I'll add that to #266

I think it still will be valuable to have `mix.exs` added here to the project alike [hackney](https://github.com/benoitc/hackney/blob/master/mix.exs) has. That will allow Elixir `mix` users consume `erlcloud` out of the box. 
@nickveys will you be able to assist?

**Comment by nickveys** [comment]
Sure, I can take a crack at the mix file if you'd like.

**Comment by waisbrot** [comment]
@nickveys : I think the real problem here was a Rebar3 or Hex bug that was marking the build tool as "rebar" when it needed to be marked "rebar3". I've published 0.13.3 to Hex and I see that it's got "rebar3" as the build tool.  Can you see if things work for you now?

**Comment by nickveys** [comment]
Updating to 0.13.3 and depending on erlcloud like so:

```{:erlcloud, "~> 0.13"},```

Still results in the original failure...  Using with a specified manager like above:

```{:erlcloud, "~> 0.13", manager: :rebar3},```

Works great. So something isn't picking it up still.  Where do you see that it has "rebar3" as the build tool?

* Mix v1.2.3
* Hex v0.11.5

**Comment by waisbrot** [comment]
Here's the Hex package I pushed: https://hex.pm/packages/erlcloud/0.13.3
"Build Tools" lists "rebar3"

Here's some other Hex package: https://hex.pm/packages/xref_runner
"Build Tools" lists "rebar" and "erlang.mk"

If I try
```
curl https://hex.pm/api/packages/erlcloud/releases/0.13.3
```
Then I get this:
```
{
   "downloads" : 35,
   "url" : "https://hex.pm/api/packages/erlcloud/releases/0.13.3",
   "version" : "0.13.3",
   "docs_url" : "https://s3.amazonaws.com/s3.hex.pm/docs/erlcloud-0.13.3.tar.gz",
   "requirements" : {
      "lhttpc" : {
         "app" : "lhttpc",
         "optional" : false,
         "requirement" : "1.4.0"
      },
      "jsx" : {
         "optional" : false,
         "requirement" : "2.8.0",
         "app" : "jsx"
      }
   },
   "inserted_at" : "2016-04-12T12:27:18.272267Z",
   "meta" : {
      "app" : "erlcloud",
      "elixir" : null,
      "build_tools" : [
         "rebar3"
      ]
   },
   "has_docs" : true,
   "package_url" : "https://hex.pm/packages/erlcloud",
   "updated_at" : "2016-04-12T14:55:38.610771Z"
}
```

Since `build_tools` is coming back with `rebar3`, I wonder if this is a Mix bug or a missing feature?

**Comment by nickveys** [comment]
Ok, I see now.  That seems pretty clear that, if that's a supported feature, it's not working!  That metadata doesn't seem to be used, do you know how/if it's specified from the erlcloud source?

**Comment by waisbrot** [comment]
The value is getting set by the Rebar3 Hex plugin: https://github.com/hexpm/rebar3_hex/blob/e9ce30f9f8fac946ada233fbc2ee0941dbabd16e/src/rebar3_hex_pkg.erl#L140

`build_tools` is listed as part of the [Hex specification](https://github.com/hexpm/specifications/blob/master/package_metadata.md#format), but I don't know if Mix pays attention to it.

**Comment by nickveys** [comment]
Looking at what is downloaded fresh from a `mix deps.get`, there isn't any build tool metadata like that that comes along with the package.  Seems like a half-complete feature or it's only meant for informative purposes on the hex.pm site, something else needs to enforce it during a build.

**Comment by ericmj** [comment]
I was linked to this issue from slack.

Mix didn't compile with rebar3 unless it was explicitly defined in the dependency `{:erlcloud, ..., manager: :rebar3}` because the rebar3 support was experimental and rebar3 was still in beta. In elixir 1.3.0 (master branch) it will check for rebar3 in the package build_tools metadata so you no longer have to explicitly set it.

**Comment by waisbrot** [comment]
Thanks for the update @ericmj! That makes sense. I've already forgotten how recently rebar3 was just a beta.

**Comment by waisbrot** [comment]
I tried depending on erlcloud with mix 1.3.3 and I get only the dependencies that erlcloud should actually have.

@nickveys  please reopen if you find that this is not the case for you.

**Comment by nickveys** [comment]
Working fine lately for me too, thanks @waisbrot.
