### ISSUE TITLE
Unsubscribe SNS topic

### ISSUE THREAD

**Issue by Linuus** [erlcloud/erlcloud#277]
Hi!

Is this API endpoint missing from the library? I can't find it.
http://docs.aws.amazon.com/sns/latest/api/API_Unsubscribe.html

If it is, would it be possible to have it implemented?

**Comment by motobob** [comment]
hello @Linuus 

yes, unfortunately upstream does not have that implemented yet. 
We have that made in our [alertlogic](https://github.com/alertlogic/erlcloud/blob/master/src/erlcloud_sns.erl#L511-L518) fork which is way ahead of upstream.
so if switching forks is fine with you you can try that. 

In the mean time, i'll try schedule it for you but a PR is more then welcome as the change is trivial.

**Comment by Linuus** [comment]
@motobob Oh, nice! I'll try your fork then :)

I'll see if I can get some time to send a PR as well :+1:

**Comment by waisbrot** [comment]
The AlertLogic fork has been merged in, including code for this.

**Comment by Linuus** [comment]
👍
