### ISSUE TITLE
Erlang/OTP 19.0 requires switching from random:uniform/1 to rand:uniform/1

### ISSUE THREAD

**Issue by okeuday** [erlcloud/erlcloud#278]
The random module is deprecated, for removal in 20.0, so when warnings are turned on the compilation will fail with 19.0.  If an erlcloud_random.erl module is added to switch between random:uniform/1 and rand:uniform/1 based on preprocessor version macros, it can be easy to support older versions too.  An example of the macros which might be used is at https://github.com/okeuday/uuid/blob/master/rebar.config#L4-L22 .  Is there any reason to not pursue this approach?

**Comment by okeuday** [comment]
`erlcloud_util.erl` appears to be meant for compatibility purposes, but due to its runtime checking it still creates warnings.  That appears to be the proper place, based on the hash functions there.

**Comment by smilerlee** [comment]
We've been working on the obsolete usages and backward compatibilities problems, like what we did [here](https://github.com/erlcloud/erlcloud/commit/36b00f81c8ff38f0ab0b5b954fc7e8e1e4e87804).

A PR for this is welcome.

**Comment by okeuday** [comment]
I added changes for this at https://github.com/erlcloud/erlcloud/pull/287

**Comment by motobob** [comment]
adressed
