### ISSUE TITLE
0.13.5 release

### ISSUE THREAD

**Issue by okeuday** [erlcloud/erlcloud#292]
Could a new hex/git-tag 0.13.5 be created at a stable commit, to get the Erlang/OTP 19.0 changes, to avoid compile warnings?  This is partially related to concerns in https://github.com/erlcloud/erlcloud/pull/288 .

**Comment by motobob** [comment]
here you go.
https://github.com/erlcloud/erlcloud/releases/tag/0.13.5
hex to come shortly

**Comment by motobob** [comment]
@waisbrot looks like i have no permissions to publish to hex `erlcloud`
```
Proceed? ("Y")> Y
===> Status Code: Forbidden (403)
Hex Error: account not authorized for this action
```
can you please publish `0.13.5` and add my email to list of hex owners by
```
rebar3 hex owner add erlcloud ebob@alertlogic.com
```

**Comment by waisbrot** [comment]
@motobob I just added your email. Want to try publishing this to check that it works?

**Comment by motobob** [comment]
That was quick, thank you!
published successfully
