### ISSUE TITLE
Incorrect character encoding with erlcloud_http:url_encode/1

### ISSUE THREAD

**Issue by ishikawa** [erlcloud/erlcloud#296]
Erlcloud uses `erlcloud_http:url_encode/1` to encode data to [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding), but its result is incorrect for some Unicode characters.

### Examples

I usually play with Elixir and Ruby, so the example is `iex` and `irb`. The Unicode codepoint `U+8000` ("耀") should be encoded as `%E8%80%80`, but `erlcloud_http:url_encode/1` output is `%F0%88%80%80`.

**Erlcloud**

```elixir
% iex -S mix run -e 'IO.puts :erlcloud_http.url_encode("\u{8000}")'
Erlang/OTP 19 [erts-8.0.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
...
%F0%88%80%80
```

**Ruby**

```ruby
% ruby -r uri -e 'puts URI.encode("\u{8000}")'
%E8%80%80
```

### Environment

- Erlang/OTP 19 `Erlang/OTP 19 [erts-8.0.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]`
- Elixir 1.3.1
- Erlcloud [0.13.6](https://github.com/erlcloud/erlcloud/releases/tag/0.13.6)
- Ruby 2.0.0p648

**Comment by smilerlee** [comment]
fixed, thanks for your reporting

**Comment by ishikawa** [comment]
Thanks! 😄
