### ISSUE TITLE
EC2 describe* APIs should provide pagination

### ISSUE THREAD

**Issue by motobob** [erlcloud/erlcloud#302]
currently all EC2 describe\* API do not support `MaxResults` and pagination.
so if you run `ercloud_ec2:describe_instances([],[], Cfg)` for an account with thousands hosts you may fail. Even  user will limit by some filters like VPC it still has a big change to faill

propose to add support for pagination to greatly reduce pain of using the library for big deployments.

**Comment by SergeyOvchinnik** [comment]
@motobob I think it's time to close this one

**Comment by motobob** [comment]
implemented
