### ISSUE TITLE
Support for Cloudwatch Logs

### ISSUE THREAD

**Issue by ephe-meral** [erlcloud/erlcloud#304]
It seems as if support for the cloudwatch logs API is missing (or at least not to be found under 'mon'). Is there any plan to add this?

**Comment by motobob** [comment]
yeah, *_mon module was not updated for a while and AWS introduced a lot there. 
Not sure if anybody working on adding that at the moment as this one was always "add when needed"

**Comment by motobob** [comment]
several changes went in for CW. https://github.com/erlcloud/erlcloud/releases/tag/3.1.9 
more updates are welcome
