### ISSUE TITLE
eini hex.pm package causes any dependency on erlcloud package to break

### ISSUE THREAD

**Issue by okeuday** [erlcloud/erlcloud#307]
Due to eini not depending completely on hex.pm packages, the usage of a package that depends on erlcloud's hex.pm package breaks with an error like:

    ==> eini (compile)
    Dependency not available: proper-.* ({git,
                                          "git://github.com/manopapad/proper.git",
                                          {tag,"1.1.1-beta"}})
    Dependency not available: covertool-.* ({git,
                                             "https://github.com/idubrov/covertool.git",
                                             {branch,"master"}})
    ERROR: compile failed while processing .../deps/eini: rebar_abort
    ** (Mix) Could not compile dependency :eini, "rebar compile skip_deps=true deps_dir=".../_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile eini", update it with "mix deps.update eini" or clean it with "mix deps.clean eini"

**Comment by okeuday** [comment]
@waisbrot It might be good to fork https://github.com/accense/eini into the `erlcloud` organization if it is difficult to change that repo.  The only potential problem is determining how to do the hex.pm package which would require a separate name, perhaps `eini_erlcloud`.

**Comment by okeuday** [comment]
Oh, if necessary, a handoff of the `eini` package can take place by contacting support@hex.pm

**Comment by waisbrot** [comment]
@motobob tkojima says that eini is no longer maintained and there's no objection to someone taking it over (https://github.com/accense/eini/issues/4#issuecomment-246220091). How about pulling it under the erlcloud org? I think it's a reasonable fit since the ini format is used by AWS and most other Erlang projects don't have any reason to use that config format.

The Hex repo is not a problem; I'm the one who put the current package up and I retain access since nobody on eini wanted it.

**Comment by motobob** [comment]
@waisbrot i've forked `accence/eini` to `erlcloud`. Please retarget your PR here and update our rebar.config in `erlcloud`. 
I've also made you member of `erlcloud` org given amount of your contribution. I think it will make your life easier here and thank you for covering hex universe for us.

**Comment by okeuday** [comment]
After the `eini` dependency gets fixed, please create a new `erlcloud` release with a hex package, as long as the master branch isn't in a broken state.  That should be the first hex package of erlcloud which can be used as a dependency with Erlang/OTP 19.0

**Comment by motobob** [comment]
that is git auto-closed this not me...wierd...
