### ISSUE TITLE
Bad publication of 0.13.8

### ISSUE THREAD

**Issue by waisbrot** [erlcloud/erlcloud#313]
erlcloud 0.13.8 never got published to Hex. I published it, but it turns out that my Rebar3/Hex plug-in combo was broken and so the metadata for the package is incorrect (it doesn't list any dependencies).

I sent a note to Hex asking them to take it down but maybe it's easier to just cut 0.13.9.

**Comment by motobob** [comment]
i'll fix up #314 as i merged it to fast, sorry

**Comment by motobob** [comment]
hm, seem to have same issue with :
```
Dependencies:
    
```
so did not publish 0.13.9 manually yet
and it's too late to revert 0.13.8
and travis still not publishing but at least building :)

continue digging...

**Comment by motobob** [comment]
managed to publish manually.

**Comment by waisbrot** [comment]
Motobob's publication works. 
Hex won't unpublish the bad version. They'll eventually have a feature to mark versions as deprecated for cases like this, but that doesn't exist today.

Closing this, since the current latest version is good.
