### ISSUE TITLE
Signing AWS request takes a surprisingly long time.

### ISSUE THREAD

**Issue by MikeBenza** [erlcloud/erlcloud#325]
We have an application in development that executes multiple queries to DynamoDB in parallel.  I noticed the queries seemed to take unusually long even though they were returning no data ~~(sometimes up to 1 second to execute all 16 parallel queries on an m4.xlarge instance)~~.

I profiled it and noticed ~~two things:~~ the time to sign a single request is long (~9ms) ~~, and when executed in parallel the performance is much much worse.  This issue is to deal with the case of a single signing taking a long time~~.

I created the attached analysis with the following code.  al_erlcloud is a library we have that helps generate our default AWS configuration.

``` erl
fprof:trace([start, {file, "/tmp/single.trace"}, verbose]).
erlcloud_aws:sign_v4_headers(al_erlcloud:default_config(), [], <<"Test body">>, "us-east-1.dynamodb.aws.com", "dynamodb").
fprof:trace([stop]).
fprof:profile({file, "/tmp/single.trace"}).
fprof:analyse([totals, {dest, "/tmp/single.analysis.txt"}]).

```

[single.analysis.txt](https://github.com/erlcloud/erlcloud/files/533968/single.analysis.txt)

Edit: I think I was misreading the fprof outputs for the parallel tests, so the parallel case doesn't seem much worse, just not as good as I'd hoped -- 94ms to sign 16 requests in parallel (5.85ms per signing) compared to 9ms to sign one request.

**Comment by motobob** [comment]
i guess under
```erlang
erlcloud_aws:sign_v4_headers(al_erlcloud:default_config(), [], <<"Test body">>, "us-east-1.dynamodb.aws.com", "dynamodb").
```
you meant
```erlang
erlcloud_aws:sign_v4_headers(erlcloud_aws:default_config(), [], <<"Test body">>, "us-east-1.dynamodb.aws.com", "dynamodb").
```

**Comment by motobob** [comment]
anyway, thanks you for reporting the issue. after some time looking into the problem looks like with https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L539-L540

we will address it as soon as we can. 
probably after i merge AL fork in.

**Comment by fp** [comment]
I have done some work to analyze the signing process, and I can see that on R16B03-1 this runs about 1.7x slower than if the same code is executed on 19.1 (e.g. 1000 iterations in 312ms on R16B03-1 and 183ms on 19.1).

I also have a new version of the sign_v4 code that runs about 1.16x faster than what is in erlcloud_aws now.  I'm still working on studying this implementation, but will likely result in a new sign_v4 PR coming in the next few weeks.

SUT: mac os sierra, iMac 4Ghz processor

**Comment by motobob** [comment]
#349 addresses this is some form by using other way of reworking `base16`

**Comment by motobob** [comment]
after added base16 dep 
[single.analysis.new.txt](https://github.com/erlcloud/erlcloud/files/641886/single.analysis.new.txt)

happy to close?

**Comment by MikeBenza** [comment]
👍
