### ISSUE TITLE
erlcloud_s3:explore_dirstructure() doesn't take AwsConfig argument

### ISSUE THREAD

**Issue by jonathn-al** [erlcloud/erlcloud#346]
erlcloud_s3:explore_dirstructure() doesn't have a variant taking an AwsConfig argument similar to most other functions.

**Comment by SergeyOvchinnik** [comment]
Doesn't look like erlcloud_s3:explore_dirstructure uses Config anywhere anyway, why would passing Config to it be required?

**Comment by jonathn-al** [comment]
It would be passed on to erlcloud_s3:list_objects(..., Config) here:
  https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_s3.erl#L327

**Comment by SergeyOvchinnik** [comment]
Oh, I see what you mean. Yeah, can implement that

**Comment by motobob** [comment]
addressed
