### ISSUE TITLE
erlcloud_cloudformation:describe_stacks_all() doesn't return "Parameters"

### ISSUE THREAD

**Issue by jonathn-al** [erlcloud/erlcloud#347]
erlcloud_cloudformation:describe_stacks_all() doesn't return the stack's "Parameters" similar to the return value from 'aws cloudformation describe-stacks --stack-name teststack'
(it does return the stack's "Outputs" as expected).

**Comment by motobob** [comment]
Confirm that parsing in this module is greatly outdated and simplified. 
thanks for reporting. 
If you have a change ready - PR is welcome.
Otherwise we will add it to our backlog ti right after all sigV4 updates several other changes planned.
