### ISSUE TITLE
x-amz-storage-class on s3:put_object?

### ISSUE THREAD

**Issue by amokan** [erlcloud/erlcloud#358]
I'm sure I'm missing something obvious here, but I'm struggling to set the `x-amz-storage-class` to `REDUCED_REDUNDANCY` on a put_object call. I've tried passing as a header with no luck.

Anybody have experience with this? I see references to `storage_class` in the code - but it appears to be mostly related to bucket metadata GETs.

**Comment by motobob** [comment]
```erlang
>{ok, Cfg}= erlcloud_aws:profile().
>erlcloud_s3:put_object("ebob-stacks", "reduced-obj", "asdfasdfasdfasdfasdfasdfasdfafs", [], [{"x-amz-storage-class", "REDUCED_REDUNDANCY"}], Cfg).
[{version_id,"null"}]
```
works for me. 
please provide detailed error or close the issue

**Comment by amokan** [comment]
thanks @motobob - I'm not sure on the issue I had before, but it does seem to work now.
