### ISSUE TITLE
Debugging erlcloud_ddb2:batch_write_item/3 -> {error, unprocessed} 

### ISSUE THREAD

**Issue by jhw** [erlcloud/erlcloud#379]
Hi,

Trying to put data to DynamoDB2 with the above. Most of time it works, but some of the time I am getting the above. How do I debug the reason for the failure if I don't get a record back ? I'm not currently sending any data to the third (Config) arg; should I be specifying something there that would force erlcloud to return more information ?

Many thanks.

**Comment by posilva** [comment]
Hi,

maybe it can help if you use a lib/tool like [recon](https://github.com/ferd/recon) to debug production, with a little patience and the following command you can catch the output of the request that got the error:

`recon_trace:calls{erlcloud_ddb_impl,request, fun([_,M,_]) when M =:= "DynamoDB_20120810.BatchWriteItem" -> return_trace() end)},10). `

Cheers

Pedro

**Comment by nalundgaard** [comment]
@jhw You really need to pass the `{out, record}` or `{out, typed_record}` option  when using this function. It is a simple wrapper around the AWS [BatchWriteItem](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html), which may return [UnprocessedItems](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html#DDB-BatchWriteItem-response-UnprocessedItems). The default `simple` output doesn't return complex responses. See [here](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_ddb2.erl#L1369-L1372):

```erlang
    case out(Return, 
             fun(Json, UOpts) -> undynamize_record(batch_write_item_record(), Json, UOpts) end, 
             DdbOpts) of
        {simple, #ddb2_batch_write_item{unprocessed_items = [_|_]}} ->
            %% TODO resend unprocessed items automatically (or controlled by option). 
            %% For now return an error - you can handle manually if you don't use simple.
            {error, unprocessed};
        {simple, Record} -> {ok, Record};
        {ok, _} = Out -> Out;
        {error, _} = Out -> Out
    end.
```

Another thing I would strongly recommend to you is to switch to [`erlcloud_ddb2:write_all.2,3,4`](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_ddb_util.erl#L415-L467) (see also put_all, delete_all in the same module, for even simpler interface). These functions are higher level ones (hence their inclusion in a `_util` module) that will automatically retry on unprocessed items. If you switch to these, you will probably never see these errors again.

**Comment by nalundgaard** [comment]
One follow up—I trust you are controlling the number of items you write at a time? DynamoDB limits each batch write request to 25 items. I've not tried passing more than 25 to the API, so I'm not sure if they will reject the whole request, or process 25 of them and return the extra items as `UnprocessedItems`. Either way, even if you stay within the 25 item limit, you may still get `UnprocessedItems` now and then.

The `erlcloud_ddb2:<write/put/delete>_all` functions I mentioned in my last comment will handle chunking your input if you pass > 25 and parallel write them to DynamoDB, in addition to handling the retries on `UnprocessedItems`.

I hope that helps!

**Comment by jhw** [comment]
Thank you. Yes am controlling the number of items sent. Yes I should be
using Config arg to return list of unprocessed items. Yes I realise
erlcloud won't resubmit items, I need to do it myself.

Real issue here is that I need to increase the throughput args when
creating the table - suspect that will solve it.

Thanks!

#closed

**Comment by nalundgaard** [comment]
No problem!
