### ISSUE TITLE
Response format

### ISSUE THREAD

**Issue by gutiago** [erlcloud/erlcloud#392]
I'm using the erlcloud_mon module and when I get the response, it comes with the following format
```
[{"label","CPUUtilization"},
 {"datapoints",
  [[{timestamp,{{2017,2,9},{12,0,0}}},
    {unit,"Percent"},
    {"average","0.5419583333333334"}],
   [{timestamp,{{2017,2,9},{0,0,0}}},
    {unit,"Percent"},
    {"average","0.7089305555555555"}]]}]
```

Is there a way to have a json response instead of this one? Here is the example of the response I got from Amazon Command Line and the one I need.

```
{
    "Datapoints": [
        {
            "Timestamp": "2017-02-09T04:00:00Z", 
            "Average": 0.7084305555555556, 
            "Unit": "Percent"
        }, 
        {
            "Timestamp": "2017-02-09T16:00:00Z", 
            "Average": 0.5484027777777778, 
            "Unit": "Percent"
        }
    ], 
    "Label": "CPUUtilization"
}
```

**Comment by motobob** [comment]
what is wrong with proplist representation of JSON in erlang?
please clarify why would you want a raw binary instead of a parsed JSON.

**Comment by gutiago** [comment]
I was having problem to retrieve the values of the list, sorry I am new to erlang. I didn't know it was a proplist representation. So I'll test the proplist's funcs instead. Thank you for the reply. Btw, the way I know, I decode the Json and use list:keyfind, so that's the reason I asked the question.

**Comment by nalundgaard** [comment]
@gutiago also have a look at [kvc](https://github.com/etrepum/kvc) and [jsn](https://github.com/nalundgaard/jsn) if you're looking for more robust ways to interact with nested JSON represented as an Erlang proplist. It may help with the atom/binary key ambiguity as well.

**Comment by motobob** [comment]
@gutiago yes, there are many ways to deal with proplists, couple ^. 
closing this

**Comment by gutiago** [comment]
I'll take a look @nalundgaard! Thank you for the tip! Thank you too @motobob.
