### ISSUE TITLE
Support for ECS task specific IAM credentials in erlcloud_aws.autoconfig()

### ISSUE THREAD

**Issue by ringods** [erlcloud/erlcloud#406]
In July 2016, AWS accounced IAM Roles for ECS tasks:

https://aws.amazon.com/about-aws/whats-new/2016/07/amazon-ec2-container-service-now-supports-iam-roles-for-tasks/

This prevents that the underlying ECS Cluster Instances need all the possible IAM permissions for the different ECS services it runs: each ECS task can be linked to it's own permissions and secrets.

As a result, fetching the credentials from the EC2 instance metadata doesn't suffice anymore. You also have a container specific URL now where you can fetch the task specific IAM credentials from:

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

The chain to follow in fetching credentials is:
* env variables
* AWS profile
* ECS credentials only if the ECS Relative URI is set
* EC2 Instance Metadata

As an example, here is the implementation of this in the AWS SDK for Javascript:
https://github.com/aws/aws-sdk-js/blob/515fcbcbcc4b01a05ace7b98c1284387f70cb541/lib/node_loader.js#L36
https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/ecs_credentials.js

**Comment by motobob** [comment]
yeah, that would an important update to have. let us see what can be done.

**Comment by rvangraan** [comment]
Hi there, can someone describe what needs to be done to support this and point to where in the code this should go? I need this now and I can help if it isn't a big job.

**Comment by motobob** [comment]
at least this one need to be updated
https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L306-L448
https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L652-L690
this one can help too
https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_ec2_meta.erl

**Comment by keichan34** [comment]
@rvangraan not sure how far along you were, but we needed this too so I took a stab at implementing it in #420
