### ISSUE TITLE
Is erlcloud intended to be "Erlang cloud computing library" as stated in the app.src?

### ISSUE THREAD

**Issue by posilva** [erlcloud/erlcloud#416]
Hi,

I need to create a erlcloud similar lib to "manage"  Linode API. I usually use erlcloud for AWS do you think that makes sense to also include in erlcloud lib?

Of course I can create a separate project but it would be great if we only have the one and only "Erlang Cloud Computing Library" => Erlcloud.

Comments

**Comment by motobob** [comment]
i would like `erlcloud` continue being AWS only. that was discussed over long time ago with Azure/Google clouds. 
We can change the text in app.src if you'd like.

**Comment by posilva** [comment]
No need to change it, I was just asking to know what is the direction!

I am ok with that.

Thank you
