### ISSUE TITLE
Support Amazon S3 Transfer Acceleration

### ISSUE THREAD

**Issue by onetamer** [erlcloud/erlcloud#417]
AWS S3 has a feature that allows speeding up downloads/uploads up to 6x.
In order to use this feature, users have to enable Transfer Acceleration in the AWS console.
This will provide a new connection URL for the bucket which usually looks like this:
**bucket-name.s3-accelerate.amazonaws.com**
It would be great if the erlcoud_s3 module supported this. Thank you.
This is an enhancement request.

**Comment by motobob** [comment]
should be archivable with current code if you set `s3_host` to `"s3-accelerate.amazonaws.com"` and `s3_bucket_access_method` to `vhost` in the config, like:
```erlang
erlcloud_s3:list_objects("mybucket", Cfg#aws_config{s3_host = "s3-accelerate.amazonaws.com", s3_bucket_access_method = `vhost`}).
```

**Comment by motobob** [comment]
yep, that works

**Comment by tommysrn** [comment]
@motobob I can't get it to work on 3.1.4. Does it work for you on 3.1.4? Thank you!
I'm getting this error:
```
** exception error: {aws_error,{socket_error,{nxdomain, ...
```
