### ISSUE TITLE
Number of HTTP connections involved in `erlcloud_ddb2:get_item`

### ISSUE THREAD

**Issue by rvangraan** [erlcloud/erlcloud#418]
Hi,

I'm just doing a few stress tests in order to understand the behaviour of the erlcloud_ddb2. I'm doing a lot of `erlcloud_ddb2:get_item` requests and at some point my computer ran out of socket descriptors. I then checked why and saw a bunch of connections like this:
```
beam.smp  86868  rvg  247u     IPv4 0x3137e513e9988935        0t0       TCP ip-10-76-9-75.eu-west-1.compute.internal:58297->54.239.33.172:https (ESTABLISHED)
beam.smp  86868  rvg  248u     IPv4 0x3137e513e9986e4d        0t0       TCP ip-10-76-9-75.eu-west-1.compute.internal:58298->54.239.33.172:https (ESTABLISHED)
beam.smp  86868  rvg  249u     IPv4 0x3137e513e9985c5d        0t0       TCP ip-10-76-9-75.eu-west-1.compute.internal:58300->54.239.33.172:https (ESTABLISHED)
beam.smp  86868  rvg  250u     IPv4 0x3137e513e998922d        0t0       TCP ip-10-76-9-75.eu-west-1.compute.internal:58301->54.239.33.172:https (ESTABLISHED)
beam.smp  86868  rvg  251u     IPv4 0x3137e514028f722d        0t0       TCP ip-10-76-9-75.eu-west-1.compute.internal:58303->54.239.33.172:https (ESTABLISHED)
beam.smp  86868  rvg  252u     IPv4 0x3137e514028f4e4d        0t0       TCP ip-10-76-9-75.eu-west-1.compute.internal:58302->54.239.33.172:https (ESTABLISHED)
```
(More than 150 in fact). 

All of these are to AWS Dynamo - 54.239.33.172 is `dynamodb.eu-west-1.amazonaws.com`.

So why does erlcloud open so many connections and why does it not close them? It looks like they eventually die, but only many minutes after I stopped requests. 

Also, doesn't erlcloud reuse existing connections? I.e. maintain a (small'ish) pool of connections?

**Comment by posilva** [comment]
Hi, 
here it is my 2 cents:

- So why does erlcloud open so many connections and why does it not close them?

If you are using erlcloud with the default HTTP client (lhttpc) then the socket connection is reused what means the connection stays established: [`find_socket`](https://github.com/erlcloud/lhttpc/blob/master/src/lhttpc_manager.erl#L316) and 
[`deliver_socket`](https://github.com/erlcloud/lhttpc/blob/master/src/lhttpc_manager.erl#L521) logic

-  maintain a (small'ish) pool of connections? 

Yes, you can manage the pool size depending on the HTTP client used, we can even use a function that is used to wrap a http request call [aws_config](https://github.com/erlcloud/erlcloud/blob/master/include/erlcloud_aws.hrl#L105)  

I hope should be a brief introduction to how erlcloud http request are managed. erlcloud is "almost" agnostic (at least can be) in terms of how HTTP calls are done.

Cheers

Pedro

**Comment by motobob** [comment]
erlcloud by default uses lhttpc [pool of 1000 con](https://github.com/erlcloud/lhttpc/blob/master/src/lhttpc.app.src#L40) and is does reuse the connection. 
this can be switched to hackney if you wish with `#aws_config{}` manipulation.
If you wish to use less connections - just update your configs.

the connection close is controlled by your sysctl and by default close_wait is 60 sec. 

in our deployments we run at 10K connection with no issues.
the fact the you run out of sockets on your machine with default settings tells me that your `ulimit` is a default 1024. just update it to more reasonable value and it will be good. (`ulimit -n X`)

let me know if you need more assist on this issue
