### ISSUE TITLE
auto_config crash if detection is not successful.  

### ISSUE THREAD

**Issue by fogfish** [erlcloud/erlcloud#435]
I'd like to get your feedback if this is desired behaviour.

`erlcloud_aws:auto_config()` fails if the node (e.g. docker container) do not have was credentials.

```
application:ensure_all_started(erlcloud).
erlcloud_aws:auto_config().
** exception error: no match of right hand side value undefined
     in function  erlcloud_aws:auto_config/1 (./_build/default/lib/erlcloud/src/erlcloud_aws.erl, line 420)
```

Let it fail sound a logical behaviour. However, would it improve api if function returns error?

**Comment by motobob** [comment]
that's a bug.
auto_config() should not fail such and return `undefined` or default_config()
please check in the latest tagged release , couple intermittent one before were issues with profiles&auto_config.

**Comment by motobob** [comment]
seems like here is the root of the failure https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L442

**Comment by motobob** [comment]
where is does not comply with https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L420 case and should just pass through the `undefined`

**Comment by fogfish** [comment]
yes, this is root cause.

**Comment by fogfish** [comment]
#440 should fix this as well.

**Comment by motobob** [comment]
addressed
