### ISSUE TITLE
invalid environment variables during the config.

### ISSUE THREAD

**Issue by fogfish** [erlcloud/erlcloud#439]
> The AWS CLI supports the following environment variables.
> * `AWS_ACCESS_KEY_ID` – AWS access key.
> * `AWS_SECRET_ACCESS_KEY` – AWS secret key. Access and secret key variables override credentials stored in credential and config files.
> * `AWS_SESSION_TOKEN` – Specify a session token if you are using temporary security credentials.
> * `AWS_DEFAULT_REGION` – AWS region. This variable overrides the default region of the in-use profile, if set.

See the [official documentation](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html)

The official [boto client support these variables](https://github.com/boto/botocore/blob/c76553d3158b083d818f88c898d8f6d7918478fd/botocore/credentials.py#L260-262)

erlcloud fails because it uses outdated variables `AWS_SECURITY_TOKEN` and `AWS_REGION`

**Comment by motobob** [comment]
fixed by ^
i'll tag/hex it tomorrow to give  a day to further test master
