### ISSUE TITLE
CloudWatch (erlcloud_mon) fails with credential should be scoped to a valid region

### ISSUE THREAD

**Issue by fogfish** [erlcloud/erlcloud#454]
I think the monitoring service uses a dedicated [endpoint per region](http://docs.aws.amazon.com/general/latest/gr/rande.html#cw_region). The library [do not rewrite](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L634) a host for monitoring service. I am afraid this is a reason of this error.

**Comment by fogfish** [comment]
Gentlemen, What is your release cycles? When this fix going to be delivered to HEX?

**Comment by motobob** [comment]
usually right after 2-3 fixes. i just got distracted, sorry.
hex published.
