### ISSUE TITLE
3.0.3 is using lhttpc version that is not Erlang 20 compatible

### ISSUE THREAD

**Issue by rolkar** [erlcloud/erlcloud#458]
I get this warning when compiling with Erlang 20

===> Compiling lhttpc
_build/default/lib/lhttpc/src/lhttpc_manager.erl:270: Warning: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_bytes/1

lhttpc 1.5.4 is not Erlang 20 compatible

**Comment by motobob** [comment]
well. this finally happened :)
@nalundgaard FYI too

**Comment by motobob** [comment]
Actually. lhttpc is fine here. this is a warning for a fallback code. 20+ lhttpc does use strong bytes.
