### ISSUE TITLE
erlcloud_sns:publish is throwing timeout error

### ISSUE THREAD

**Issue by shahdarshan1711** [erlcloud/erlcloud#459]
I am trying to use erlcloud to send push notification to mobile based on endpointArn which received from client. I am able to successfully push notification with Java application. But same stuff if I try with erlang, it is giving timeout error. Below are code samples.

`Config = erlcloud_sns:new(<<"Access Key">>,<<"secret Key">>,<<"sns.us-west-2.amazonaws.com">>).`

`erlcloud_sns:publish(target,<<"arn:aws:sns:us-west-2:2315XXXXXX:endpoint/GCM/testapp/XXXXXXX-fe9a-304e-aa52-XXXXXXXX">>,<<"ok">>,undefined,[],Config).`

Last statement is showing below error.

`** exception error: {sns_error,{socket_error,timeout}}
 in function  erlcloud_sns:sns_xml_request/3 (src/erlcloud_sns.erl, line 670)
 in call from erlcloud_sns:publish/6 (src/erlcloud_sns.erl, line 471)`

Same value of access_key, secret_key, Host and endpointArn works from Java program.

**Comment by saa** [comment]
The same issue. And sometimes got `InternalError Request could not be completed`.

**Comment by motobob** [comment]
try strings instead of binaries for keys, arns, host.

sns publish works on my test setup so i need more details.

**Comment by shahdarshan1711** [comment]
Thanks for your help. It's working now with strings instead of binaries. Closing this issue.
