### ISSUE TITLE
SNS internal error

### ISSUE THREAD

**Issue by saa** [erlcloud/erlcloud#462]
When i publish to topic not often I see `"InternalError","Request could not be completed"`. How I should handle it properly?

**Comment by motobob** [comment]
that's how AWS works. just retry.
on our 1000+/s publish rate we constantly see a small percentage of 503s.

**Comment by motobob** [comment]
you can add a default  retry via https://github.com/erlcloud/erlcloud/blob/master/include/erlcloud_aws.hrl#L123 and change this to use [default_retry](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_retry.erl#L44-L49)
or add your custom one.
