### ISSUE TITLE
Breaking API changes between 0.13.* and 2.0.0

### ISSUE THREAD

**Issue by sebmaynard** [erlcloud/erlcloud#463]
On the readme, it says "list to be filled shortly"

I've submitted a few pull requests on this project, but can't submit any at the moment without risking breaking something as I'm still on 0.13.10 

Any more details on this please? :)

**Comment by motobob** [comment]
yeah...that's a miss. 
it was ELB/ AutoScalling, some S3 changes. rest are pretty fine. 

Application common/ functional testing should covers this and will be very easy to find if that breaks your app. 

PRs are welcome.
