### ISSUE TITLE
Version specified in .app.src file breaks using the repo not in git

### ISSUE THREAD

**Issue by sebmaynard** [erlcloud/erlcloud#464]
You specify the version of this application in the .app.src as {vsn, git}

This breaks rebar with any project that isn't using git directly to fetch repositories (we use perforce, so rsync in the deps from a local checkout).. and this forces me to maintain versions that I decide to use with pinned versions

Is there any chance of changing this behaviour?

**Comment by motobob** [comment]
`rebar`, `rebar3` and `hex` use it well.
long long time ago it's was common to maintain the app.src file and update it with every tag which adds unnecessary overhead. 
so, the answer will be no, i don't think we'll change that back. 
I would maybe suggest adding rebar.config.script or similar for your case.

**Comment by motobob** [comment]
question answered ^
