### ISSUE TITLE
which erlcloud module is the most up to best practices?

### ISSUE THREAD

**Issue by alexturkin** [erlcloud/erlcloud#473]
If I want to introduce module with new functionality, which module should I use as "best practice" which I could just follow? (In terms of names, output etc).

I also propose to add this info to ["Best Practices"](https://github.com/erlcloud/erlcloud#best-practices) section. Erlcloud library is known for diversity of approaches, shall one be officially proclaimed as the "one"?

**Comment by motobob** [comment]
I'm not sure picking the "latest"/ "hotest" will help resolving the diversity.
i'll think of updating the readme but IMO its time to make radical changes.

**Comment by motobob** [comment]
Please add the section into the readme.
