### ISSUE TITLE
compilation error with rebar3

### ISSUE THREAD

**Issue by immnas** [erlcloud/erlcloud#518]
Hi,
I am getting compilation error 
When I have added at my rebar.config
{deps, [
  {erlcloud, {git, "https://github.com/erlcloud/erlcloud.git", {tag, "v0.10.0"}}}
]

after that I run rebar3 upgrade, rebar3 compile and I am getting following error. 

===> Compiling erlcloud
===> Compiling _build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl failed
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:30: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:37: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:45: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:54: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:64: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:68: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:73: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:76: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:85: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:94: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:98: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:103: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:107: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:112: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:116: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:121: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:129: syntax error before: '/'
_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:139: syntax error before: '/'

_build/default/lib/erlcloud/src/erlcloud_cloudtrail.erl:25: Warning: type ct_return() is unused

Makefile:31: recipe for target 'compile' failed

**Comment by motobob** [comment]
v0.10.0 - is three years ago...
see latest releases. https://github.com/erlcloud/erlcloud/releases
