### ISSUE TITLE
Problem with string:to_lower

### ISSUE THREAD

**Issue by duduceolin** [erlcloud/erlcloud#525]
https://github.com/erlcloud/erlcloud/blob/674b2c539de7095d3df75bac96abe4c21f2efa36/src/erlcloud_mon.erl#L395

When i'm calling get_metrics, there is a method which is called by it. The method name is extract_metrics

(stdlib) string.erl:1798: :string.to_lower/1
    (erlcloud) /home/eduardo/smaug/deps/erlcloud/src/erlcloud_mon.erl:395: :erlcloud_mon."-extract_metrics/2-lc$^0/1-0-"/2
    (erlcloud) /home/eduardo/smaug/deps/erlcloud/src/erlcloud_mon.erl:395: :erlcloud_mon.extract_metrics/2
    (erlcloud) /home/eduardo/smaug/deps/erlcloud/src/erlcloud_mon.erl:387: :erlcloud_mon."-get_metric_statistics/9-lc$^2/1-2-"/2
    (erlcloud) /home/eduardo/smaug/deps/erlcloud/src/erlcloud_mon.erl:387: :erlcloud_mon.get_metric_statistics/9

**Comment by nalundgaard** [comment]
Is the actual error you're experiencing getting accidentally filtered out? I see that it's getting called, but this is a normal Erlang OTP function. Is it getting called with a non-string?

**Comment by duduceolin** [comment]
Yes. it was my fault.

Sorry.
