### ISSUE TITLE
[discuss] using hackney to replace httpc

### ISSUE THREAD

**Issue by benoitc** [erlcloud/erlcloud#55]
@gleber I wonder if you would be interested by a patch replacing httpc by [hackney](http://github.com/benoitc/hackney) . It would give the following advantages compared to httpc:
- reuse the connections via a pool
- easy streaming (so objects could be streamed to s3)
- multipart support

Thoughts?

**Comment by benoitc** [comment]
hep, what about allowing people to switch the client at the compile time. The issue spotted above with hackney has been solved, but instead to only support one client i am thinking it could be possible to allows someone to also use its own HTTP client facility. So people that need specific pooling or any other feature could just give a module at compile time to use (to remove any performance issue).

Thoughts?

**Comment by ransomr** [comment]
Currently you can specify client at run time. I would be surprised if the performance benefit of specifying at compile time would matter much (compared to everything else the http client needs to do). But if there is a good reason, I'm okay with supporting compile time configuration.
