### ISSUE TITLE
#551 fix s3 region parsing

### ISSUE THREAD

**Issue by pzLib** [erlcloud/erlcloud#552]
s3.cn-north-1.amazonaws.com.cn and s3.cn-northwest-1.amazonaws.com.cn are China s3 endpoints, I add some parsing code into erlcloud_s3:aws_region_from_host.  
Please see #551 
Thank you.

**Comment by motobob** [comment]
will publish a tag to hex in a bit .  thanks for contribution. 
happy to see this is used in China.

**Comment by pzLib** [comment]
> will publish a tag to hex in a bit . thanks for contribution.
> happy to see this is used in China.

Thank you for your reply. In fact, many Chinese Companies are using AWS(global), I have used it more than 5 years.
