### ISSUE TITLE
Fix dialyzer specs

### ISSUE THREAD

**Issue by k32** [erlcloud/erlcloud#559]
In several places (erlcloud_s3 in particular, maybe somewhere else) there are typespecs that look like:

`-spec foo() -> something() | no_return().`

In success typing they don't make sense [1] [2], as `none()` type indicates that the function _never_ returns a value (e.g. loops forever, _always_ crashes or shuts down BEAM emulator). Annotating functions that have at least one code path returning a term with `no_return()` 1) can hide genuine dialyzer errors 2) is viral, as all code calling the function becomes `no_return()`, hiding more errors 

[1] http://erlang.org/doc/reference_manual/typespec.html
[2] https://learnyousomeerlang.com/dialyzer

I can create a PR to clean this stuff up.

**Comment by paulo-ferraz-oliveira** [comment]
Many of those `no_return()` were actually put there by me, because I thought I could signal "this function throws an exception"; you're right, though, that it skews proper `dialyzer` results. Do you know of a better way to signal that a function throws an exception?

**Comment by k32** [comment]
@paulo-ferraz-oliveira 

> Do you know of a way, though, to signal that a function throws an exception?

Unfortunately, as of today dialyzer doesn't support specifications for exceptions. There is no better option that `@throws` edoc tag to document this.
