### ISSUE TITLE
erlcloud_lambda:invoke does not work under erlang release 21.3.8

### ISSUE THREAD

**Issue by nicolasmd87** [erlcloud/erlcloud#594]
Just to clarify , I know the Readme specifies that the supported erlang versions are: 19.3, 20.3 and 21.1.

Having said that , I can assure that version erlang 21.3.8 is not compatible with the function erlcloud_lambda:invoke as it returns for every Lambda invocation {socket_error, timeout}, after switching to 21.3 it started working normally again. Are upgrades expected for compatibility with new erlang releases coming in the future?  should we look for an alternative for erlcloud? given we depend on newer erlang versions for some of our dependencies.

**Comment by motobob** [comment]
@nalundgaard FYI too

@nicolasmd87 this is erlang ssl specific and related to lhttpC
we have it working on 21.3.8.4 i think but i'll reconfirm

**Comment by nicolasmd87** [comment]
@motobob thank you very much sir, looking forward to the confirmation.

**Comment by motobob** [comment]
@nicolasmd87 it work on 21.1, 21.3, 21.3.8.4 on my setup. will add it to travis too. 
make sure you've compile  your VM with 
`export CFLAGS="-DOPENSSL_NO_EC2M=1 -O3"`, former is what is important.
Erlang's SSL is a dumpsterfire after 21....

**Comment by nicolasmd87** [comment]
Perfect, thx for the response.
