### ISSUE TITLE
Setting the throughput of an application autoscaler

### ISSUE THREAD

**Issue by Santiniis** [erlcloud/erlcloud#596]
Hey! I went through the codebase and I got the idea that the only possible autoscaler type that is able to be updated is the ec2 instances autoscaler.

I have a problem right now in which I need to be able to set an application's minimum capacity [based on this module of AWS](https://docs.aws.amazon.com/autoscaling/application/APIReference/Welcome.html). Namely, I need to be able to use operations such as [PutScheduledAction](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html#autoscaling-PutScheduledAction-request-ServiceNamespace).

Am I wrong and I didn't see it clearly and it's already implemented in the lib? If it isn't, I can contribute to the repo in order to add this functionality.

**Comment by motobob** [comment]
unfortunately. this is not yet here. library is added with new functionality as needed. contribution welcome.

**Comment by Santiniis** [comment]
Implemented on pull request #597 .
