### ISSUE TITLE
Support for bucket tagging and object tagging APIs, enable proxy configuration and updating List response header for tagging APIs.

### ISSUE THREAD

**Issue by saherkar** [erlcloud/erlcloud#606]
I want to submit the changes that I did for supporting:
1. Bucket and Object tagging APIs and respective change in lists call.
2. Enabling Proxy Configuration.

Should I create PR for these changes, will you be accepting these?
Do I need to sign any documentation to add these changes?

Thanks.

**Comment by motobob** [comment]
just PR that following the standard of the erlcloud_s3 module and we will merge.
contribution is appreciated. 

no signatures needed

**Comment by saherkar** [comment]
Thanks for update. I have created required PR.

**Comment by motobob** [comment]
addressed
