### ISSUE TITLE
Application Autoscaler doesn't show when a scheduled action is run/starts and ends

### ISSUE THREAD

**Issue by Santiniis** [erlcloud/erlcloud#608]
I'm opening this pull request since I just noticed that the API endpoint [DescribeScheduledActions](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScheduledActions.html) is missing the fields related to when a scheduled action is run / starts and ends running. I will try to provide a fix for this.

**Comment by motobob** [comment]
fixed by #609
