### ISSUE TITLE
SQS Sender Attribute may not be an integer

### ISSUE THREAD

**Issue by posilva** [erlcloud/erlcloud#618]
I am getting this error recently when polling SQS for messages in several services:

`
#{class => error,exception_pattern => badarg,
stacktrace => [{erlang,list_to_integer,["Root=1-5d5c5482-23a6930a2884c022fcd44464;Parent=5d87b9851445351e;Sampled=0"],[]},{erlcloud_sqs,'-decode_msg_attributes/1-lc$^0/1-0-',1,[{file,"/opt/jenkins_home/workspace/server/_build/default/lib/erlcloud/src/erlcloud_sqs.erl"},{line,395}]},{erlcloud_sqs,'-decode_msg_attributes/1-lc$^0/1-0-',1,[{file,"/opt/jenkins_home/workspace/server/_build/default/lib/erlcloud/src/erlcloud_sqs.erl"},{line,396}]}
`
Looking at the code erlcloud is decoding SenderId as integer but now it seems it can be a more complex structure. 

Anyone is getting this error?
I will be happy to submit a patch.

**Comment by motobob** [comment]
isn't already just been fixed?  at https://github.com/erlcloud/erlcloud/pull/615 .

git pull. unless we forgot to tags and relx push it

**Comment by nalundgaard** [comment]
Should be in [3.2.11](https://github.com/erlcloud/erlcloud/releases/tag/3.2.11) that I published to fix #616.

**Comment by posilva** [comment]
Sorry, my bad. 

I was looking into the version I have the service and not to master.

Closing.
