### ISSUE TITLE
Bad request on erlcloud_kms generate_data_key

### ISSUE THREAD

**Issue by marutha** [erlcloud/erlcloud#644]
Facing below error, I tried using aws cli, it works fine on aws cli. any debug pointers?

`erlcloud_kms:generate_data_key("myarn is here", [{key_spec,"AES_128"}]).                          
{error,{http_error,400,"Bad Request",
                   <<"{\"__type\":\"SerializationException\",\"Message\":\"Start of list found where not expected\"}">>,
                   [{"content-length","86"},
                    {"content-type","application/x-amz-json-1.1"},
                    {"date","Tue, 23 Jun 2020 10:49:25 GMT"},
                    {"pragma","no-cache"},
                    {"expires","0"},
                    {"cache-control",
                     "no-cache, no-store, must-revalidate, private"},
                    {"x-amzn-requestid",
                     "41572dab-eeda-4feb-b48b-ed36388672d3"}]}}`

**Comment by nalundgaard** [comment]
Just a first guess based on the biggest pain point in Erlang: Use binary strings, not list strings.

```erlang
erlcloud_kms:generate_data_key(<<"myarn is here">>, [{key_spec, <<"AES_128">>}]).
```

The JSON encoder is JSX, and it treats lists as integer arrays when it encodes.

**Comment by marutha** [comment]
Ah! that works, thanks!
