### ISSUE TITLE
What is the purpose of the output tests?

### ISSUE THREAD

**Issue by kennedyjosh** [erlcloud/erlcloud#651]
I've been messing around with some of the output tests, and it seems like no matter what I do to them, they all pass. I've been replacing correct text/numbers with nonsense, but tests still seem to pass. It seems like the output tests are basically checking the copy/paste skills of the programmer, as they set both the expected and the actual results. 

What am I missing here?

**Comment by nalundgaard** [comment]
Generally they should not pass when you malform the data, though to some extent it will depend on how you malform it. They're intended to mock the expected AWS API output and reason about the response format of the function, given that output from the AWS API. It is mostly a test of the decoding logic, and it can be pretty rote, but generally helpful. That said, it's possible that someone made an interstitial error somewhere in a module or two that has rendered them meaningless.

Spot checking erlcloud_ddb2_tests, it definitely works as I expect. can you name some particular ones that you have in mind? The modules are substantially distinct, to be honest.

**Comment by kennedyjosh** [comment]
Admittedly, I am unable to replicate my previous issue (I also forgot which test function I was toying with). Still, it seems that some tests are not tests, but serve more as guides for what the output will look like. Taking a look at `erlcloud_mms_tests:meter_usage_output_tests/1` (line 280) its hard to see how this is a helpful test. I changed the inputs of the function its supposed to be testing, but the test still passes, even when I change the data types to be completely incorrect. It's easy to see here that the expected and result are essentially retyped.

The real issue is that I am trying to write output tests of my own, but I'm not exactly sure what I'm testing since none of my inputs are expected to reappear in the results. It's really easy to write tests that don't actually work but pass, but I want to make sure that I'm actually testing something.

**Comment by nalundgaard** [comment]
That is a legitimate test. It [mocks the response of `erlcloud_httpc:request(...)`](https://github.com/erlcloud/erlcloud/blob/e4d903c/test/erlcloud_mms_tests.erl#L118), then executes [`erlcloud_mms:meter_usage(...)`](https://github.com/erlcloud/erlcloud/blob/e4d903c/test/erlcloud_mms_tests.erl#L287) and expects back [the given output expectation](https://github.com/erlcloud/erlcloud/blob/e4d903c/test/erlcloud_mms_tests.erl#L284).

Admittedly, it's a little misleading that the inputs to `erlcloud_mms:meter_usage(...)` are essentially ignored, assuming they don't cause an actual crash (the mock is categorical). The point is really to mock the AWS response to be a value, and assert that, given that value, we get back the decoded value. It's certainly overwrought in some cases, but it's testing the behavior of the erlang API in relationship to raw output from AWS. That's a simple, but extremely useful test, and combined with the input tests, it's solid coverage.

If you have a superior framework for unit tests, we would welcome improved tests here, but as far as I can tell, it's a simple test that tests a really simple part of a simple function. Unit tests are supposed to be simple and isolated, IMO. Granted, it's pretty ironic that the test harness is more complex than the code itself, but c'est la vie, it's at least minimally repetitive.

**Comment by kennedyjosh** [comment]
Thank you for your response; I think I have a better understanding of the output tests now. I think this is a good framework, despite being a bit complex, and I can see the value in it. I'll close the issue as my initial questions/concerns have been resolved.
