### ISSUE TITLE
Support SES requests with Signature v4

### ISSUE THREAD

**Issue by enerick** [erlcloud/erlcloud#652]
AWS has announced its ending of support for SES APIs using Signature v3 on September 30, 2020.
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html

It seems that erlcound_ses is still using Signature v3, so we should migrate to v4.
https://github.com/erlcloud/erlcloud/blob/0f0540041ad6b55700715d1d3629853bf3158791/src/erlcloud_ses.erl#L1256-L1260

**Comment by nalundgaard** [comment]
Thanks for the note! I am surprised that our org hadn't noticed that yet via AWS notice. I'll look at fixing it soon.

**Comment by enerick** [comment]
Thanks!
