### ISSUE TITLE
erlcloud_iam:get_role response does not include RoleLastUsed

### ISSUE THREAD

**Issue by aaronlelevier** [erlcloud/erlcloud#670]
Hi,

I noticed that `erlcloud_iam:get_role` method that calls the [GetRole](https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetRole.html) AWS API doesn't include the "RoleLastUsed" information. Would it be possible to add this?

The info is present in AWS's documentation and I did a spike of this and could serialize the field. I can submit a PR if that works.

Thanks

**Comment by nalundgaard** [comment]
+1 from me, looks like you just need to update [`data_type("Role")`](https://github.com/erlcloud/erlcloud/blob/0f05400/src/erlcloud_iam.erl#L977-L983) with a `"RoleLastUsed"` entry, and I guess also a `data_type("RoleLastUsed")` implementation that has the 2 sub-properties in it. It looks like [`erlcloud_iam_tests`](https://github.com/erlcloud/erlcloud/blob/0f05400/test/erlcloud_iam_tests.erl) is missing unit tests for `get_role`, so it would be extra-awesome to cover it using the sample response in the AWS docs. Thanks for the offer of a PR!

**Comment by aaronlelevier** [comment]
Ok, PR submitted. Thanks
