### ISSUE TITLE
Export request creation functions on erlcloud_ddb2

### ISSUE THREAD

**Issue by DarkGV** [erlcloud/erlcloud#672]
Hi,

I'm developing a library on top of erlcloud that need packet creation functions inside **erlcloud_ddb2** to be exported.
As a matter of example, I need a function that processes the input of **erlcloud_ddb2:get_item** instead of sending the packet directly to DynamoDB to return to the caller function.

Is this possible?

Thank you for your time!

**Comment by nalundgaard** [comment]
This sounds possible to do, I guess, but would probably need some bit of work to integrate elegantly. Do you have something in mind? Maybe you can pitch a PR with the first implementation for feedback.

**Comment by DarkGV** [comment]
I will try to find a way to do it elegantly as I have something in mind. As soon as I get it working I'll pitch a PR.
