### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlcloud/erlcloud#675]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by nalundgaard** [comment]
I definitely would, travis is already pretty broken for PRs AFAICT. @motobob any objection?

**Comment by paulo-ferraz-oliveira** [comment]
I'll make it so you can decide later on whether to keep `.travis.yml` or reject it (i.e. I won't be "replacing" the CI, but rather adding upon it).

**Comment by motobob** [comment]
yes - that would be great! and if can substitute travis it's even better
