### ISSUE TITLE
Issues with importing lhttpc_types.hrl

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlcloud/erlcloud#692]
Hi. We have our own implementation of `lhttpc` which is a fork of the original. When we import `erlcloud` we import our own `lhttpc` (not the one `erlcloud` bundles). Now the thing is we recently removed `lhttpc_types.hrl` from our version (we put the types in `lhttpc` as we felt 1. stuff like `result()` was way to generic to not eventually cause a conflict, 2. we didn't want to keep an `.hrl` based part of the interface), for simplicity.

Would it be OK if I pull requested to get rid of the types, as imported by `erlcloud`? One strategy could be to update your `lhttpc` (I'd pull request there too) to import `lhttpc_types.hrl` to `lhttpc` and then export the types `erlcloud` requires from there. This way we don't break interface (though we kinda duplicate types).

Let me know. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Better still, I think this should be a `behaviour`-based solution. If there's expectation from `erlcloud` for an alternative HTTP client they could thus be made more explicit.

**Comment by nalundgaard** [comment]
I'm generally on board with that, and TBH, I think generally open to migrating erlcloud/lhttpc to the changes you guys have made in your fork, with the one possible exception that I am not sure about pivoting to strict https certificate enforcement by default—while it's important, I am a little concerned it might yield some unpleasant surprises. What do you think, @motobob?

**Comment by motobob** [comment]
go for it!

**Comment by paulo-ferraz-oliveira** [comment]
I'll work on the behaviour for your `lhttpc` and then propose that in `erlcloud`. After that you might decide to either keep it or move away from it. Behaviour shouldn't be hard to achieve, I hope (and it can also be applied to whatever other HTTP client is used, since it would have to implement the same interface).

**Comment by paulo-ferraz-oliveira** [comment]
I dug into this and this is where I'm at.


__1
`erlcloud_aws` uses `headers()` and `result()` from `lhttpc_types.hrl`


__2
`headers()` is basically
```
-type header() :: 'Cache-Control' | 'Connection' | 'Date' | 'Pragma'
...
-type headers() :: [{header(), iodata()}].
```
so potentially simplifiable to `[{atom(), iodata()}]`, since not used internally by `lhttpc` and `dialyzer` will turn that list into `atom()` (happens after 13 items).


__3
`result()` is
```
-type result() ::
        {ok, {{pos_integer(), string()}, headers(), body()}} |
        {ok, upload_state()} |
        {error, atom()}.
```
where `upload_state()` is `{pid(), non_neg_integer() | 'infinity'}`


I think importing the `.hrl` just for this is not worth it, but it's ultimately your call. I'll pull request with changes to `erlcloud` alone and let's go from there.

**Comment by paulo-ferraz-oliveira** [comment]
Also, yeah, our recently Hex-published `lhttpc` fork is here: https://hex.pm/packages/mc_lhttpc.

> strict https certificate enforcement by default

You should be able to bypass this with (as per our `MIGRATION.md`)
```
lhttpc:request("https://self-signed.badssl.com", "GET", [], <<>>, 5000, [{verify_ssl_cert, false}]).
```
which you could potentially add as an `erlcloud` option.

**Comment by paulo-ferraz-oliveira** [comment]
It actually seems we're using `string()` in some places, for headers, though the `lhttpc` `headers` are defined as atoms-as-keys. We can broaden the type, I guess.
