### ISSUE TITLE
Failure to read Secret Manager value

### ISSUE THREAD

**Issue by pankajsoni19** [erlcloud/erlcloud#706]
EC2 instance has IAM access role assigned with access to secret manager data.

```
SMKey = "production/database".
Config = erlcloud_aws:default_config().
Config1 = erlcloud_aws:service_config(<<"sm">>, "us-east-2", Config).
erlcloud_sm:get_secret_value(SMKey, Config1).
```

This fails with error

```
=WARNING REPORT==== 31-Aug-2021::07:47:46.518895 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

{error,{socket_error,{nxdomain,[{lhttpc_client,send_request,
                                               1,
                                               [{file,"src/lhttpc_client.erl"},{line,252}]},
                                {lhttpc_client,execute,9,
                                               [{file,"src/lhttpc_client.erl"},{line,201}]},
                                {lhttpc_client,request,9,
                                               [{file,"src/lhttpc_client.erl"},{line,101}]}]}}}
```

if using http it fails with

```
{error,{socket_error,{failed_connect,[{to_address,{"sm.us-east-2.amazonaws.com",
                                                   443}},
                                      {inet,[inet],nxdomain}]}}}
```

**Comment by pankajsoni19** [comment]
OTP version `24.0.2`
System info `Debian GNU/Linux 9.13 (stretch)`
Distribution `Linux ip-41-2-0-190 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux`

**Comment by posilva** [comment]
This seems a DNS resolution issue. Are you sure the `sm.us-east-2.amazonaws.com` it's the correct one or would be `secretsmanager.us-east-2.amazonaws.com` instead for secrets manager?

Both errors are `nxdomain` related the "error" you mentioned `Authenticity is not established by certificate path validation` is just a warning. Not related with the `nxdomain` error you are getting.

**Comment by posilva** [comment]
This should be fixed with https://github.com/erlcloud/erlcloud/pull/707

**Comment by posilva** [comment]
@pankajsoni19 should we close this issue?

**Comment by nalundgaard** [comment]
Looks like yes, please reopen if you still have it.
