### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by hrieke** [erlcloud/erlcloud#715]
Hi guys,

Your hex_metadata.config lists the license as MIT License, the COPYRIGHT file shows the BSD 2-clause.
https://hex.pm/packages/erlcloud

Thanks,

**Comment by motobob** [comment]
yeah. that's an error. to be fixed at next publish

**Comment by nalundgaard** [comment]
https://hex.pm/packages/erlcloud/3.5.10 now shows BSD 2-Clause. Thanks for bringing this to our attention!
